### ISSUE TITLE
Tweet-sheet utility

### ISSUE THREAD

**Issue by rmsy** [bored-engineer/iOS-sbutils#1]
I'm just suggesting a utility to call a 'Tweet-sheet' with pre-specified content which could be passed via argument. Not sure how hard this is to do, but it would be cool =)

**Comment by ersmets** [comment]
This works: 

https://github.com/lukapusic/twitter-bot

You do need to tell curl to ignore ssl certificates.

**Comment by bored-engineer** [comment]
What he means is to open the tweet-sheet utility added in iOS 5. Unfortunately from what I've seen so far you have to be hooked into SpringBoards process space to do this properly. Here's some code that does it when hooked into SpringBoard: https://github.com/rpetrich/libactivator/blob/master/LASimpleListener.x#L448
