### ISSUE TITLE
Idea: show open app/mode

### ISSUE THREAD

**Issue by j-chad** [bored-engineer/iOS-sbutils#13]
it would be nice if you could shh into your device and tell if its unlocked or in a specific app.
i believe activator has this, but i do not want activator.

for example, you could do something like:

> > > currentmode
> > > returns 'locksreen','homescreen','app'
> > > 
> > > currentapp
> > > returns 'com.xxxxxxx.xxxxxxx' or even the app name

Thanks

**Comment by moshed** [comment]
you can use sshmediacontrols for that I believe.
