### ISSUE TITLE
iOS 9 - Killed 9

### ISSUE THREAD

**Issue by domgregori** [bored-engineer/iOS-sbutils#15]
sbutils doesn't seem to be working on iOS 9.3.3. When you run it you get a "Killed 9" response. I've tried using ldid -S with no success.

**Comment by bored-engineer** [comment]
Unfortunately (as is probably obvious from the other open issues) I haven't maintained or touched sbutils in a few years. I'm guessing this has something to do with needing to be re-compiled for arm64 and the latest frameworks but I don't know or even have a jailbroken device to test :/

**Comment by bored-engineer** [comment]
It looks like awesomebing1 maintained an active fork for a while, perhaps you could file an issue with his fork: https://github.com/awesomebing1/iOS-sbutils

**Comment by domgregori** [comment]
Thanks so much for the reply! I'll take a look at the fork.

**Comment by domgregori** [comment]
Looks like the fork works as-is! Thanks again

**Comment by frakman1** [comment]
This makes me so happy! Thank you for sharing the new location. It worked for me too!
