### ISSUE TITLE
Idea: retrieving IMEI

### ISSUE THREAD

**Issue by ersmets** [bored-engineer/iOS-sbutils#4]
The deviceinfo utility doesn't work anymore on iPhone 4S.

Even the ioreg command outputs a blank IMEI. I think the correct way to retrieve it, and other parameters such as IMSI, is via CoreTelephony..

Could you please make an utility to retrieve the IMEI ? 

TIA

@eriksmets

**Comment by bored-engineer** [comment]
By "The deviceinfo utility doesn't work anymore on iPhone 4S." do you mean the utility as a whole?

**Comment by ersmets** [comment]
Nope, just the imei-retrieving part. I can't find the imei value with ioreg either.

**Comment by bored-engineer** [comment]
sbdevice has no code to retrieve IMEI. Only UUID.
